use crate::{
    system_states::aarch64::ScfiaAarch64SystemState,
    transformation_functions::transformation_function_expression::ScfiaTransformationFunctionExpression,
    values::value64::Value64,
};

use super::transformation_function_memory_write::ScfiaAarch64TransformationFunctionMemoryWrite;

#[derive(Debug)]
pub struct ScfiaAarch64TransformationFunction {
    pub successors: Vec<ScfiaAarch64TransformationFunctionSuccessorDefinition>,
}

#[derive(Debug)]
pub struct ScfiaAarch64TransformationFunctionSuccessorDefinition {
    pub new_r0: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r1: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r2: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r3: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r4: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r5: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r6: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r7: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r8: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r9: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r10: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r11: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r12: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r13: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r14: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r15: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r16: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r17: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r18: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r19: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r20: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r21: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r22: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r23: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r24: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r25: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r26: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r27: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_r28: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_fp: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_lr: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_sp_el3: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_pc: Option<u64>,
    pub new_pstate_n: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_pstate_z: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_pstate_c: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_pstate_v: Option<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
    pub new_pstate_pan: Option<bool>,
    pub new_pstate_ssbs: Option<bool>,
    pub new_pstate_tco: Option<bool>,
    pub new_pstate_uao: Option<bool>,
    pub new_pstate_i: Option<bool>,
    pub new_pstate_dit: Option<bool>,
    pub new_pstate_sp: Option<bool>,
    pub new_pstate_it: Option<u8>,
    pub new_pstate_t: Option<bool>,
    pub new_pstate_f: Option<bool>,
    pub new_pstate_d: Option<bool>,
    pub new_pstate_nrw: Option<bool>,
    pub new_pstate_btype: Option<u8>,
    pub new_pstate_j: Option<bool>,
    pub new_pstate_e: Option<bool>,
    pub new_pstate_el: Option<u8>,
    pub new_pstate_q: Option<bool>,
    pub new_pstate_ss: Option<bool>,
    pub new_pstate_m: Option<u8>,
    pub new_pstate_a: Option<bool>,
    pub new_pstate_il: Option<bool>,
    pub new_sctlr_el3: Option<u64>,
    pub memory_writes: Vec<ScfiaAarch64TransformationFunctionMemoryWrite>,
    pub new_asserts: Vec<ScfiaTransformationFunctionExpression<ScfiaAarch64SystemState>>,
}

impl ScfiaAarch64TransformationFunctionSuccessorDefinition {
    pub fn new() -> Self {
        ScfiaAarch64TransformationFunctionSuccessorDefinition {
            new_r0: None,
            new_r1: None,
            new_r2: None,
            new_r3: None,
            new_r4: None,
            new_r5: None,
            new_r6: None,
            new_r7: None,
            new_r8: None,
            new_r9: None,
            new_r10: None,
            new_r11: None,
            new_r12: None,
            new_r13: None,
            new_r14: None,
            new_r15: None,
            new_r16: None,
            new_r17: None,
            new_r18: None,
            new_r19: None,
            new_r20: None,
            new_r21: None,
            new_r22: None,
            new_r23: None,
            new_r24: None,
            new_r25: None,
            new_r26: None,
            new_r27: None,
            new_r28: None,
            new_fp: None,
            new_lr: None,
            new_sp_el3: None,
            new_pc: None,
            new_pstate_n: None,
            new_pstate_z: None,
            new_pstate_c: None,
            new_pstate_v: None,
            new_pstate_pan: None,
            new_pstate_ssbs: None,
            new_pstate_tco: None,
            new_pstate_uao: None,
            new_pstate_i: None,
            new_pstate_dit: None,
            new_pstate_sp: None,
            new_pstate_it: None,
            new_pstate_t: None,
            new_pstate_f: None,
            new_pstate_d: None,
            new_pstate_nrw: None,
            new_pstate_btype: None,
            new_pstate_j: None,
            new_pstate_e: None,
            new_pstate_el: None,
            new_pstate_q: None,
            new_pstate_ss: None,
            new_pstate_m: None,
            new_pstate_a: None,
            new_pstate_il: None,
            new_sctlr_el3: None,
            memory_writes: vec![],
            new_asserts: vec![],
        }
    }
}
