[package]
name = "scfia-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
z3-sys = { path = "../z3.rs/z3-sys" }
# z3-sys = { git = "https://github.com/Trolldemorted/z3.rs", branch = "buildfix3" }
serde_json = "*"
log = "0.4"

[dev-dependencies]
xmas-elf = "0.7"
simple_logger = "4.1"